# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (once a day)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: berkanktk
          template: classic
          base: header, activity, community, repositories
          config_display: large
          config_padding: 0, 6 + 11%
          config_timezone: Europe/Copenhagen
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 10
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_lines: yes
          plugin_lines_history_limit: 5
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
